<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Auth\Events\Registered;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;

class RegisterController extends Controller
{
    /**
     * Показ формы регистрации
     */
    public function showRegistrationForm()
    {
        return view('auth.register');
    }

    /**
     * Обработка регистрации без пароля (email + телефон)
     */
    public function register(Request $request)
    {
        // --- 1. Валидация данных ---
        $validated = $request->validate([
            'name'      => ['required', 'string', 'max:255'],
            'email'     => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'telephone' => ['required'],
        ]);

        // --- 2. Очистка номера ---
        $tel = preg_replace('/\D/', '', $request->input('telephone'));

        if (strlen($tel) != 12) {
            return back()->withErrors(['telephone' => 'Введите корректный номер телефона, например +380671234567']);
        }

        // --- 3. Создание пользователя без ввода пароля ---
        $user = User::create([
            'name'      => $validated['name'],
            'email'     => $validated['email'],
            'telephone' => $tel,
            // Временный автогенерируемый пароль (чтобы Laravel не ругался)
            'password'  => Hash::make('autogenerated_' . $tel),
        ]);

        // --- 4. Событие регистрации ---
        event(new Registered($user));

        // --- 5. Авторизация и переход к verify-email ---
        Auth::login($user);
        return redirect()->route('verification.notice')
            ->with('success', 'Регистрация успешна! Проверьте email и подтвердите номер телефона.');
    }
}
